services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - POSTGRES_DB=erp_db
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
